# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: pip3 install -r ./requirements.txt
    command: >
      cd s3_upload &&
      python3 manage.py migrate &&
      python3 manage.py runserver localhost:8080
image:
  file: .gitpod.Dockerfile
